// ═══════════════════════════════════════════════════════════════════
// api/follow-up-cron.ts
//
// Vercel cron job — runs daily at 09:00 AEST (configured in vercel.json).
//
// Purpose: send the day-3 follow-up email to EOIs that:
//   - submitted ≥ 3 days ago
//   - status === 'new'  (no booking yet — booked EOIs get the booking pipe)
//   - followup_sent_at IS NULL  (don't double-send)
//
// Template selection (lead temperature):
//   HOT    → watched 90%+ of Loom AND hasn't booked   (rare but valuable)
//   WARM   → watched 75%+ of Loom, hasn't booked
//   COOL   → watched 25-75% of Loom
//   COLD   → watched <25% OR didn't open Loom
//
// Until Loom is filmed, watch_pct is always null, so everyone falls to COLD.
// That's the right default — the cold template doesn't assume they watched.
//
// Resend sender: notifications@hiretrial.com.au (Resend domain already
// verified via existing eoi-submit + approve-eoi routes).
//
// Security: Vercel automatically protects cron endpoints with a header
// `Authorization: Bearer <CRON_SECRET>`. We verify that header before
// running. CRON_SECRET is auto-generated by Vercel when cron is enabled.
//
// Env vars required:
//   SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//   RESEND_API_KEY
//   CRON_SECRET (auto-generated by Vercel when cron is enabled)
// ═══════════════════════════════════════════════════════════════════

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const SUPABASE_URL              = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESEND_API_KEY            = process.env.RESEND_API_KEY;
const CRON_SECRET               = process.env.CRON_SECRET;

const FOLLOWUP_DAYS = 3;
const FROM_ADDRESS  = 'Anders @ Trial. <notifications@hiretrial.com.au>';
const REPLY_TO      = 'anders@hiretrial.com.au';

// ─── Lead temperature classifier ──────────────────────────────────
// Currently returns 'cold' for everyone (Loom not filmed yet).
// When Loom is live, this reads loom_watch_pct from the eoi row.
type Temperature = 'hot' | 'warm' | 'cool' | 'cold';

function classifyLead(eoi: any): Temperature {
  const watchPct = eoi.loom_watch_pct || 0;
  if (watchPct >= 90) return 'hot';
  if (watchPct >= 75) return 'warm';
  if (watchPct >= 25) return 'cool';
  return 'cold';
}

// ─── Email templates (subject + HTML body) ────────────────────────
// All four templates use the same Trial. brand system: Cormorant Garamond
// serif headlines, Inter Tight sans body, gold #c8a96e on near-black #0a0a0a.
// Tone matches the landing page: candid, premium, owner-to-owner.
//
// First-name personalisation via {{firstName}}, venue name via {{venueName}}.
// Booking link points at the same Calendly URL the EOI page does.

const BOOKING_URL = 'https://hiretrial.com.au/#eoi';

interface Template {
  subject: string;
  preheader: string;
  bodyHtml: (vars: { firstName: string; venueName: string }) => string;
}

const TEMPLATES: Record<Temperature, Template> = {
  // ─── HOT: watched ≥ 90% of Loom but didn't book.
  // They've seen the whole product, they get it, they just haven't pulled
  // the trigger. Direct, no fluff, single CTA.
  hot: {
    subject: 'Hey {{firstName}} — saw you watched the whole walkthrough',
    preheader: 'A founding partner spot is still yours if you want it.',
    bodyHtml: ({ firstName, venueName }) => `
      ${shell({ firstName, venueName, title: 'You watched the whole thing.' }, `
        <p style="${pStyle}">
          ${firstName}, you watched the full walkthrough but haven't booked a call yet. That tells me one of two things — either you're still thinking, or something specific about ${escapeHtml(venueName)} is making you hesitate.
        </p>
        <p style="${pStyle}">
          Either is fine. But I'd rather hear the hesitation than not — sometimes thirty minutes of conversation answers what an eight-minute video can't.
        </p>
        <p style="${pStyle}">
          A Founding Partner spot is still yours if you want it. Same locked-for-life pricing, same direct line, same ninety-day mechanic.
        </p>
        ${ctaButton('Book a thirty-minute conversation')}
        <p style="${pSmall}">
          Or reply to this email with the one thing that's holding you back. I read every reply.
        </p>
      `)}
    `,
  },

  // ─── WARM: watched ≥ 75% — got most of it but maybe drifted at the
  // pricing or 90-day mechanic section. Lean into reassurance + the offer.
  warm: {
    subject: '{{firstName}} — quick thought after you watched the Trial. walkthrough',
    preheader: "The 90-day mechanic is the part most people want to ask about.",
    bodyHtml: ({ firstName, venueName }) => `
      ${shell({ firstName, venueName, title: 'A thought, after the walkthrough.' }, `
        <p style="${pStyle}">
          ${firstName}, thanks for watching the Trial. walkthrough. You got most of the way through, which usually means you understood the mechanic but had a question we didn't fully answer.
        </p>
        <p style="${pStyle}">
          For most operators, the question is the same one: <em style="color:#c8a96e;">"What if a hire leaves at day 89?"</em> Short answer — you pay nothing. The ninety-day mechanic is built around the moment most hospitality hiring actually fails, not the moment a candidate walks in.
        </p>
        <p style="${pStyle}">
          Founding Partner pricing is still locked for the first fifty venues. Worth a thirty-minute conversation if you're considering it — bring your specific questions and I'll show you how Trial. would actually work for ${escapeHtml(venueName)}.
        </p>
        ${ctaButton('Book a thirty-minute conversation')}
        <p style="${pSmall}">
          If you're not interested, no follow-up — just say so and I'll mark it. We're not chasing.
        </p>
      `)}
    `,
  },

  // ─── COOL: started the Loom but dropped off early. They're curious but
  // not committed. Re-pitch the *problem* (not the product) and lower the
  // bar to engagement.
  cool: {
    subject: '{{firstName}} — three days on from your Trial. signup',
    preheader: 'No pressure — just a quick check-in on the hiring problem.',
    bodyHtml: ({ firstName, venueName }) => `
      ${shell({ firstName, venueName, title: 'Three days on.' }, `
        <p style="${pStyle}">
          ${firstName}, three days ago you registered interest in Trial. We see the people who watch the whole walkthrough, the ones who watch part of it, and the ones who don't get a chance to.
        </p>
        <p style="${pStyle}">
          Either way, the reason you signed up is still true: hospitality hiring is broken, CVs lie, and you've probably lost a hire at day forty-five at some point. That's the problem Trial. is built around.
        </p>
        <p style="${pStyle}">
          If a thirty-minute call sounds like too much commitment right now, the eight-minute walkthrough is still on the EOI page — start there. If it lands, book a time. If it doesn't, no harm done.
        </p>
        ${ctaButton('Watch the walkthrough')}
        <p style="${pSmall}">
          Or reply with one sentence about what's broken in your hiring right now. I'll tell you honestly whether Trial. is built for it.
        </p>
      `)}
    `,
  },

  // ─── COLD: didn't watch the Loom, or watched <25%. They may have
  // submitted the EOI on impulse and tuned out. Re-establish the value
  // prop in the email itself rather than relying on them watching anything.
  // This is the most important template because it'll catch the most leads
  // pre-Loom-launch.
  cold: {
    subject: 'Following up — your Trial. expression of interest',
    preheader: 'Quick reminder of what you signed up for, and what happens next.',
    bodyHtml: ({ firstName, venueName }) => `
      ${shell({ firstName, venueName, title: 'A quick follow-up.' }, `
        <p style="${pStyle}">
          ${firstName} — three days ago you registered interest in Trial. for ${escapeHtml(venueName)}. Just checking in to make sure the email didn't get buried.
        </p>
        <p style="${pStyle}">
          The short version of what Trial. does: candidates apply the way they always do — Seek, your website, walk-ins. Trial. takes over from there. Role-specific assessments, a structured profile per candidate, and a ninety-day retention check before you pay per hire.
        </p>
        <p style="${pStyle}">
          You only pay for hires that stick. If a hire leaves at day eighty-nine, you've paid nothing for them. That's the part most operators want to ask about.
        </p>
        <p style="${pStyle}">
          The Founding Partner cohort — still open for the first fifty venues — locks your rate for life regardless of how Trial. is priced in twelve months or three years. The trade-off: you give us your honest operational read while we're still building.
        </p>
        ${ctaButton('Take another look')}
        <p style="${pSmall}">
          If Trial. doesn't fit ${escapeHtml(venueName)}, no worries — reply with one line and I'll mark it. We won't follow up again.
        </p>
      `)}
    `,
  },
};

// ─── Branded email shell ──────────────────────────────────────────
// Wraps body content in the Trial. brand chrome:
//   - Cormorant Garamond + Inter Tight from Google Fonts (with system fallback)
//   - Gold #c8a96e accent on near-black #0a0a0a
//   - Centered 600px column, padded
//   - Logo wordmark at top
//   - Sign-off + footer at bottom

const pStyle = `font-family:'Inter Tight',-apple-system,BlinkMacSystemFont,sans-serif;font-size:16px;line-height:1.7;color:#d4d0c4;margin:0 0 22px;font-weight:300;`;
const pSmall = `font-family:'Inter Tight',-apple-system,BlinkMacSystemFont,sans-serif;font-size:13.5px;line-height:1.6;color:#8a847a;margin:32px 0 0;font-weight:300;font-style:italic;`;

function ctaButton(text: string) {
  return `
    <table border="0" cellspacing="0" cellpadding="0" style="margin:32px 0 16px;">
      <tr>
        <td style="border-radius:0;background:#c8a96e;padding:0;">
          <a href="${BOOKING_URL}"
             style="display:inline-block;padding:16px 32px;font-family:'Inter Tight',-apple-system,sans-serif;font-size:13.5px;font-weight:500;letter-spacing:0.06em;color:#0a0a0a;text-decoration:none;text-transform:uppercase;">
            ${text} &nbsp;→
          </a>
        </td>
      </tr>
    </table>`;
}

function shell(
  vars: { firstName: string; venueName: string; title: string },
  innerHtml: string
) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Trial.</title>
</head>
<body style="margin:0;padding:0;background:#0a0a0a;font-family:'Inter Tight',-apple-system,BlinkMacSystemFont,sans-serif;">
  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background:#0a0a0a;">
    <tr>
      <td align="center" style="padding:48px 16px;">
        <table border="0" cellpadding="0" cellspacing="0" width="600" style="max-width:600px;background:#131313;border:1px solid rgba(248,246,240,0.08);">
          <tr>
            <td style="padding:48px 48px 32px;">

              <!-- Wordmark -->
              <div style="font-family:'Cormorant Garamond',Georgia,serif;font-size:28px;font-weight:600;letter-spacing:-0.02em;color:#f8f6f0;margin-bottom:40px;">
                Trial<span style="color:#c8a96e;font-size:32px;">.</span>
              </div>

              <!-- Title -->
              <h1 style="font-family:'Cormorant Garamond',Georgia,serif;font-size:34px;line-height:1.15;letter-spacing:-0.02em;color:#f8f6f0;font-weight:400;margin:0 0 28px;">
                ${escapeHtml(vars.title)}
              </h1>

              <!-- Body -->
              ${innerHtml}

              <!-- Sign-off -->
              <p style="font-family:'Cormorant Garamond',Georgia,serif;font-size:18px;font-style:italic;color:#c8a96e;margin:48px 0 0;font-weight:400;">
                — Anders, founder
              </p>

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:0 48px 40px;border-top:1px solid rgba(248,246,240,0.08);padding-top:28px;">
              <p style="font-family:'Inter Tight',-apple-system,sans-serif;font-size:11px;letter-spacing:0.06em;color:rgba(248,246,240,0.32);margin:0;text-transform:uppercase;">
                Trial. &nbsp;·&nbsp; Hospitality hiring, built by operators
              </p>
              <p style="font-family:'Inter Tight',-apple-system,sans-serif;font-size:11px;color:rgba(248,246,240,0.32);margin:8px 0 0;">
                Sydney, Australia &nbsp;·&nbsp; ABN 71 441 417 792
              </p>
            </td>
          </tr>
        </table>

        <p style="font-family:'Inter Tight',-apple-system,sans-serif;font-size:11px;color:rgba(248,246,240,0.28);margin:24px 0 0;">
          You received this because you registered interest at hiretrial.com.au.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function escapeHtml(s: string) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function fillTemplate(html: string, vars: { firstName: string; venueName: string }) {
  return html
    .replace(/\{\{firstName\}\}/g, vars.firstName)
    .replace(/\{\{venueName\}\}/g, vars.venueName);
}

// ─── Main handler ─────────────────────────────────────────────────
export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Vercel cron sends a GET with Authorization: Bearer <CRON_SECRET>
  if (CRON_SECRET) {
    const auth = req.headers['authorization'];
    if (auth !== `Bearer ${CRON_SECRET}`) {
      console.warn('[follow-up-cron] Unauthorized request — missing or wrong CRON_SECRET');
      return res.status(401).json({ ok: false, error: 'Unauthorized' });
    }
  } else {
    console.warn('[follow-up-cron] CRON_SECRET not set — running unauthenticated (dev mode)');
  }

  // Env sanity
  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY || !RESEND_API_KEY) {
    console.error('[follow-up-cron] Missing required env vars');
    return res.status(500).json({ ok: false, error: 'Server misconfiguration' });
  }

  const admin: any = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const resend = new Resend(RESEND_API_KEY);

  // ── 1. Find eligible EOIs ──────────────────────────────────────
  // Cutoff: created ≤ (now - FOLLOWUP_DAYS days)
  const cutoff = new Date(Date.now() - FOLLOWUP_DAYS * 24 * 60 * 60 * 1000).toISOString();

  const { data: eois, error: queryErr } = await admin
    .from('eoi_submissions')
    .select('id, email, contact_name, venue_name, created_at, status, calendly_booking_at, followup_sent_at, followup_attempts, loom_watch_pct')
    .eq('status', 'new')                         // hasn't booked
    .is('followup_sent_at', null)                // hasn't been sent yet
    .is('calendly_booking_at', null)             // belt-and-braces: not booked
    .lte('created_at', cutoff)                   // old enough
    .order('created_at', { ascending: true })    // oldest first
    .limit(50);                                  // safety cap per run

  if (queryErr) {
    console.error('[follow-up-cron] Query failed:', queryErr);
    return res.status(500).json({ ok: false, error: queryErr.message });
  }

  if (!eois || eois.length === 0) {
    console.log('[follow-up-cron] No EOIs eligible for follow-up today');
    return res.status(200).json({ ok: true, processed: 0 });
  }

  console.log(`[follow-up-cron] Found ${eois.length} EOIs eligible for follow-up`);

  // ── 2. Send each one (sequentially to avoid rate limits) ───────
  const results = { sent: 0, failed: 0, errors: [] as string[] };

  for (const eoi of eois) {
    try {
      const temperature = classifyLead(eoi);
      const template    = TEMPLATES[temperature];
      const firstName   = (eoi.contact_name || '').trim().split(/\s+/)[0] || 'there';
      const venueName   = eoi.venue_name || 'your venue';

      const vars = { firstName, venueName };
      const subject = fillTemplate(template.subject, vars);
      const html    = template.bodyHtml(vars);

      // Send via Resend
      const { data: sendData, error: sendErr } = await resend.emails.send({
        from:     FROM_ADDRESS,
        to:       eoi.email,
        replyTo:  REPLY_TO,
        subject,
        html,
        headers: {
          'X-Trial-Followup-Template': temperature,
          'X-Trial-EOI-ID':            eoi.id,
        },
      });

      if (sendErr) {
        console.error(`[follow-up-cron] Resend failed for ${eoi.email}:`, sendErr);
        results.failed++;
        results.errors.push(`${eoi.email}: ${sendErr.message || 'send error'}`);
        // Still bump the attempts counter so we can see the retries
        await admin.from('eoi_submissions')
          .update({ followup_attempts: (eoi.followup_attempts || 0) + 1, updated_at: new Date().toISOString() })
          .eq('id', eoi.id);
        continue;
      }

      // Mark as sent
      const { error: updErr } = await admin
        .from('eoi_submissions')
        .update({
          followup_sent_at:  new Date().toISOString(),
          followup_template: temperature,
          followup_attempts: (eoi.followup_attempts || 0) + 1,
          updated_at:        new Date().toISOString(),
        })
        .eq('id', eoi.id);

      if (updErr) {
        console.error(`[follow-up-cron] DB update failed for ${eoi.id}:`, updErr);
        // Email sent but DB didn't update — log and continue.
        // Next run won't pick it up because we'd hit a unique conflict if we tried,
        // but the data inconsistency is concerning. Worth monitoring.
      }

      results.sent++;
      console.log(`[follow-up-cron] ✅ ${temperature} → ${eoi.email} (${firstName}, ${venueName})`);

    } catch (err: any) {
      results.failed++;
      results.errors.push(`${eoi.email}: ${err.message || err}`);
      console.error(`[follow-up-cron] Unexpected error for ${eoi.email}:`, err);
    }
  }

  console.log(`[follow-up-cron] Done. Sent: ${results.sent}, Failed: ${results.failed}`);
  return res.status(200).json({
    ok: true,
    processed: eois.length,
    sent: results.sent,
    failed: results.failed,
    errors: results.errors,
  });
}
